env:
  es2017: true
  browser: true
  commonjs: true

extends: ['htmlacademy/react-typescript']
parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'

rules:
  react/prop-types: 0
